specVersion: 0.0.1
description: ''
repository: 'https://github.com/polka-domain/polka-domain-subql.git'
schema: ./schema.graphql
network:
  endpoint: 'wss://rpc.polkadomain.org/ws'
dataSources:
  - name: main
    kind: substrate/Runtime
    startBlock: 1
    mapping:
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Deposit
        - handler: handleCall
          kind: substrate/CallHandler

        - handler: domainRegisterEvent
          kind: substrate/EventHandler
          filter:
            module: domainRegistrar
            method: DomainRegistered

        - handler: domainDeregisterEvent
          kind: substrate/EventHandler
          filter:
            module: domainRegistrar
            method: DomainDeregistered
